services:
  database:
    build:
      context: ./Database
    ports:
      - "5432:5432"
    container_name: sigma-cars-database
  backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    depends_on:
      - database
    container_name: sigma-cars-backend
  frontend:
    build:
      context: ./Frontend
    ports:
      - "3000:3000"
    container_name: sigma-cars-frontend
  reverse-proxy:
    build:
      context: ./ReverseProxy
    ports:
      - "80:80"
    container_name: sigma-cars-reverse-proxy