services:
  database:
    build:
      context: ./Database
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./WebApi
    ports:
      - "5000:5000"
    depends_on:
      - database
  frontend:
    build:
      context: ./Frontend
    ports:
      - "80:3000"